FROM golang
RUN go get -u -v github.com/kardianos/govendor
RUN set -ex \
    && cd / \
    && git clone https://github.com/linecheng/weixingate.git \
    && cd /weixingate \
    && make build \
    && mv /weixingate/bin/weixin-gate /weixin-gate \
    && mkdir -p /etc/weixin-gate/tmpl \
    && mv /weixingate/bin/tmpl /etc/weixin-gate/tmpl
